### ISSUE TITLE
Automatic record and upload matches and highlights

### ISSUE THREAD

**Issue by lmachens** [lmachens/game-ticker#18]
The background process should implement the logic to record and upload matches and highlights.
It listens to [game launch](https://overwolf.github.io/docs/api/overwolf-games#ongamelaunched) events and starts a new match by sending a POST request to `/api/matches` with the `gameId` and `username`.
Highlights like kills or deaths should be [captured automatically](https://overwolf.github.io/docs/api/auto-highlights) and uploaded to Cloudinary. The link to the Cloudinary source including the type of the highlight should be added to the match by another POST request to `/api/matches/{id}/highlights`.

**Comment by webdevelukas** [comment]
solved by #38
