### ISSUE TITLE
Handling of highlights via the api

### ISSUE THREAD

**Issue by webdevelukas** [lmachens/game-ticker#40]
When we record a new highlight we're getting this object back. Actually we have defined that the type of a highlight type is a `string`. In the example below, there is more then one type of highlight in one record. How should we handle this and especially how should we handle the timestamp?

![Highlights-Object](https://user-images.githubusercontent.com/54030139/127004004-27184140-3b67-49b4-a029-9f25901d1179.png)

**Comment by lmachens** [comment]
Good catch! I would say, that we use a string array too like in `events`?

**Comment by webdevelukas** [comment]
Is solved through #42
